name: sorting_visualizer
description: A new Flutter project.
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  bloc: ^7.0.0
  dartz: ^0.10.0-nullsafety.2
  flutter:
    sdk: flutter
  flutter_bloc: ^7.1.0
  flutter_hooks: ^0.18.0
  freezed_annotation: ^0.14.2
  get: ^4.3.4
  get_it: ^7.2.0
  injectable: ^1.4.1
  json_annotation: ^4.0.1
  logger: ^1.0.0
  universal_html: ^2.0.8

dev_dependencies:
  build_runner: ^2.1.0
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  injectable_generator: ^1.4.1
  json_serializable: ^4.1.4
  lint: ^1.5.3


flutter:
  uses-material-design: true
